[package]
name = 'brickpack-sampleapp'
version = '0.1.5'
authors = ['Antonio Feitosa <antonio.cfc@gmail.com>']
edition = '2018'

[dependencies]
clap = '2.33.1'
http-types = '2.0.1'


[dependencies.brickpack]
git = 'https://github.com/afsec/brickpack'
version = '0.2'
# path = '../brickpack'
